# This is a basic workflow to help you get started with Actions

name: CI

on: workflow_dispatch

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world!"
      - run: "echo Completed the first step"
