name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: example-react-project
        run: npm install

      - name: Run tests
        working-directory: example-react-project
        run: npm test
